# Generated by Django 2.2.4 on 2019-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_enterprise_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_enterprise_member',
            field=models.BooleanField(default=False),
        ),
    ]
