# Generated by Django 2.2.4 on 2019-09-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190912_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_enterprise_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_enterprise_member',
        ),
    ]
