# Generated by Django 2.2.4 on 2019-09-13 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_enterpriseprojectrole'),
        ('accounts', '0004_auto_20190912_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_charges', models.ManyToManyField(to='projects.EnterpriseProjectRole')),
            ],
        ),
    ]
