# Generated by Django 2.2.5 on 2019-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_auto_20191105_1107'),
        ('accounts', '0008_auto_20191011_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Project'),
        ),
    ]
